version: "3.7"

services:
  app:
    build: .
    ports:
      - "5001:5001"
    volumes:
      - ./redis/redis.conf:/etc/redis/redis.conf
      - redis_data:/data
      - /root/qingtianaoi1117.1:/app  # 挂载主机工作目录
  redis:
    image: "redis:alpine"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
